"""add error_message to webhook events

Revision ID: 11bb4f593c54
Revises: 1e874c4aadfd
Create Date: 2026-08-19 12:46:50.474502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11bb4f593c54'
down_revision: Union[str, Sequence[str], None] = '1e874c4aadfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_events', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhook_events', 'error_message')
    # ### end Alembic commands ###
