"""replace merchant_name with related_account_id on transactions

Revision ID: 1df65bc21ca9
Revises: 9c4b5ad32360
Create Date: 2026-08-19 11:47:46.152201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1df65bc21ca9'
down_revision: Union[str, Sequence[str], None] = '9c4b5ad32360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('related_account_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_transactions_related_account_id_accounts'), 'transactions', 'accounts', ['related_account_id'], ['id'], ondelete='SET NULL')
    op.drop_column('transactions', 'merchant_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('merchant_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_transactions_related_account_id_accounts'), 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'related_account_id')
    # ### end Alembic commands ###
